apiVersion: v1
kind: Secret
metadata:
    name: app-cluster
    labels:
      argocd.argoproj.io/secret-type: cluster # Cluster secrets require this label to be picked up by argo.
type: Opaque
stringData:
    name: app-cluster
    server: https://C5DF5FD3176243876BFC79E7C3BCDFDF.gr7.us-west-2.eks.amazonaws.com
    config: |
      {
        "tlsClientConfig": {
          "insecure": false,
          "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1EVXdOREUzTWpjME1Gb1hEVE14TURVd01qRTNNamMwTUZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTE51Cno3NzBUYjR2MmNmYkNxa2JTQTN5Y3RobnRITDJpNHJmWjhwUUY4TkpEZkFDYWlqeEd1OFNwQkJrUFl2RWdqcmgKUlV2RWcreHh3WE9uQ2hnNHVJaENPWEk0K0RLbE85aC9PcGwxWUpLNC9GZUFDWXFTdkFIZEhjSldQejJ3cXBkZwpVb2htUldIYlQwanpkRTd1a20xT21KRWxtQlg2U253NDhsNjlyLzIrZ3pFYlZOdmZuSy92RS8zcEZ6WnpJQ0tVCjhCSU1rSDJjU2ZaWG1TVmZOSUUwY3o1Z3NYVXIxcUJIU1RhcHZ3TUhLSkQxRkhTK1dYS2dwTmZNSXBjSEYzRFMKR2ZiMjNoSUNJcXJUbnZ4Zy90KzhIclFuVldXVS81TkdyRnJDdUc1MXJMbzgxVXlHTFBhV2RSaG0wczQxeFVhUwpDaXpjMVFHZVUyLzdSdmVsRXVjQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDL3lrM0lsVWlJV0hHM3BaTStWTkd4VmVqOSsKbWoyc0dDR0xjSGhkQi9FRTVRbDZBTFdMUlB3SDdoU3JhZ29RVVZiZEJsbnY4T2crN01CR2R5N3ZUS2hGSmdKYgp0SUtTL1ZINHZKUmJTREVXblMxOWdIUyttelM5N0k4a28waDBKR21XNlVaVGtyT3BBbXVCajlEV0VwNFBScmpQCnNLOExKeERuODk2YjB1Vmc0NDBGQW1FM2xtbmVKR3FWcmltOTJFUnZrOUQ1V1NSb3A0d1hoNitLWitTWEh3bkkKZk5MS3BYMmgrS0ZPcWN3TkFEVXNrTDByemJicG82WU9MbnRwSE5NUndad242aW85WHkvaXJ0RStsclRrRlowbgpPQ1dnclJ0NUxVRXR0cFJ5S0tBMytkVGJIZlJnYUZsZHlTNjVtbGhHdnVabE54ZUc0S0pJbTdaamI5VT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
        },
        "awsAuthConfig": {
          "clusterName": "eks_argocd-app-cluster",
          "roleARN": "arn:aws:iam::137668938909:role/argocd-k8s-iam"
        }
      }
